services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=fbals
      - POSTGRES_PASSWORD=fbals
      - POSTGRES_DB=PR4
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    container_name: PR4-database

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 8080:8080
volumes:
  data:
