-- CreateTable
CREATE TABLE "Library" (
    "libraryId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "city" STRING NOT NULL,
    "address" STRING NOT NULL,

    CONSTRAINT "Library_pkey" PRIMARY KEY ("libraryId")
);

-- CreateTable
CREATE TABLE "Book" (
    "bookId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "pages" INT4 NOT NULL,
    "available" BOOL NOT NULL DEFAULT true,
    "libraryId" INT4 NOT NULL,
    "authorId" INT4 NOT NULL,

    CONSTRAINT "Book_pkey" PRIMARY KEY ("bookId")
);

-- CreateTable
CREATE TABLE "Affiliate" (
    "affiliateId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "lastName" STRING NOT NULL,
    "email" STRING NOT NULL,
    "city" STRING NOT NULL,
    "address" STRING,
    "libraryId" INT4 NOT NULL,

    CONSTRAINT "Affiliate_pkey" PRIMARY KEY ("affiliateId")
);

-- CreateTable
CREATE TABLE "Author" (
    "authorId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "lastName" STRING NOT NULL,
    "birthPlace" STRING NOT NULL,

    CONSTRAINT "Author_pkey" PRIMARY KEY ("authorId")
);

-- CreateTable
CREATE TABLE "Borrowing" (
    "borrowingId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "active" BOOL NOT NULL DEFAULT true,
    "affiliateId" INT4 NOT NULL,
    "bookId" INT4 NOT NULL,

    CONSTRAINT "Borrowing_pkey" PRIMARY KEY ("borrowingId")
);

-- AddForeignKey
ALTER TABLE "Book" ADD CONSTRAINT "Book_libraryId_fkey" FOREIGN KEY ("libraryId") REFERENCES "Library"("libraryId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Book" ADD CONSTRAINT "Book_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "Author"("authorId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Affiliate" ADD CONSTRAINT "Affiliate_libraryId_fkey" FOREIGN KEY ("libraryId") REFERENCES "Library"("libraryId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Borrowing" ADD CONSTRAINT "Borrowing_affiliateId_fkey" FOREIGN KEY ("affiliateId") REFERENCES "Affiliate"("affiliateId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Borrowing" ADD CONSTRAINT "Borrowing_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book"("bookId") ON DELETE RESTRICT ON UPDATE CASCADE;
